---
- hosts: all
  become: true
  tasks:
          - name: create user
            tags: always
            user:
                    name: simone
                    groups: root
          - name: add ssh key for simone
            tags: always
            authorized_key:
                    user: simone
                    key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOeifsu0BEaiUPoomtjpi1PqhOK3XBPSjpdxh7f61ns8 ansible

          - name: add sudoers file for simone 
            copy:
                    src: sudoer_simone
                    dest: /etc/sudoers.d/simone
                    owner: root
                    group: root
                    mode: 0440

