---
- name: Remove user simone
  hosts: all
  become: true  # This allows Ansible to execute tasks with sudo privileges

  tasks:
    - name: Remove user simone
      user:
        name: simone
        state: absent  # This ensures that the user will be removed
    
    
    - name: Remove user simone from sudoers
      lineinfile:
        dest: /etc/sudoers
        state: absent
        regexp: '^simone'
      ignore_errors: yes  # Ignore errors if the line is not found in sudoers
